### ISSUE TITLE
Remove 24 hours delay for first license check

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/license-checker#64]
Currently first license check dialog is displayed only after using some commercial component for 1 day.
Both first check delay and check interval are defined using checkInterval
https://github.com/vaadin/license-checker/blob/2.0/src/vaadin-license-checker.js#L157
https://github.com/vaadin/license-checker/blob/2.0/src/vaadin-license-checker.js#L183

As requested by @villeingman the first delay should be reduced as much as possible:
> We'd like to make changes to the checker so that the user needs to validate his license right away without any long delays. A one minute delay for example is OK as that might help with build server and test automation

Reducing to 0 or too should could affect screenshot tests. We can check the impact of having it as 10 or 5 mins initially. In practice this would be not the first load but the after a couple of reloads or restarts.

**Comment by villeingman** [comment]
Have it as close to zero as possible. A minute or two should suffice as a maximum. We want to catch all of those who do try the product, even a little. Thanks.
