### ISSUE TITLE
Incompatible with Vite

### ISSUE THREAD

**Issue by Artur-** [vaadin/license-checker#90]
If you use Vaadin 23 and Vite, then `window.Vaadin.developmentModeCallback["vaadin-license-checker"]` is never defined

In `function uncommentAndRun(callback, args) {` the value of `callback.toString()` is 

with webpack
```
function maybeCheckLicenses() {
  /** vaadin-dev-mode:start
...
  vaadin-dev-mode:end **/
}
```

with Vite
```
'function maybeCheckLicenses() {\n}'
```

`window.Vaadin.developmentModeCallback["vaadin-usage-statistics"]` works fine with both vite and webpack

**Comment by rolfsmeds** [comment]
Any thoughts on this, @vursen ?

**Comment by web-padawan** [comment]
We might need to add `"type": "module"` to `package.json` - maybe that would help (but I'm not really sure).

**Comment by Artur-** [comment]
It seems like this works if you are using the component bundle because there the commented code is intact. If you use e.g. 23.0.5 where the bundle is not used because of some version mismatches, you see this problem

**Comment by vursen** [comment]
When the component bundle is not used, the license checker ends up optimized by Vite's deps optimizer (esbuild) which happens to eliminate code comments along the way.

The usage statistics module is included in Vaadin Router which is explicitly excluded from that optimization, which explains why the stats module is not affected.

One way to fix the issue would be to add `@vaadin/vaadin-license-checker` and `@vaadin/vaadin-usage-statistics` to `optimizeDeps.exclude` in `vite.generated.ts`.
